site_name: PROOFIXEL Docs
site_url: https://docs.proofixel.cloud
copyright: Copyright &copy; 2026 PROOFIXEL
extra:
  generator: false
site_author: Proofixel Team
site_description: Documentação oficial e guias da plataforma Proofixel.
repo_name: proofixel-docs
repo_url: https://github.com/gotikozzy/proofixel-docs
edit_uri: ""
theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette: 
    - scheme: slate
      primary: deep-purple 
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro

  features:
    - navigation.instant   
    - navigation.tracking  
    - navigation.top      
    - search.suggest       
    - search.highlight    
    - content.code.copy    
markdown_extensions:
  - admonition       
  - pymdownx.details 
  - pymdownx.superfences 
  - attr_list 
nav:
  - Início: index.md
  - Primeiros Passos:
      - Como criar conta: primeiros-passos/criar-conta.md
      - Comprando Créditos: primeiros-passos/comprar-creditos.md
  - Ferramentas de Análise:
      - Entendendo o ELA: ferramentas/ela.md
      - Metadados: ferramentas/metadados.md
      - Mapa de Calor: ferramentas/heatmap.md
  - Jurídico e Privacidade:
      - Termos de Uso: legal/termos.md
      - Privacidade: legal/privacidade.md
   