site_name: PROOFIXEL Docs
site_url: https://docs.proofixel.cloud
# 1. Adicione o seu texto de Copyright (pode usar HTML, como &copy;)
copyright: Copyright &copy; 2026 PROOFIXEL

# 2. Adicione esta seção "extra" para remover o crédito do gerador
extra:
  generator: false  # Isso remove o "Made with Material for MkDocs"
site_author: Proofixel Team
site_description: Documentação oficial e guias da plataforma Proofixel.
repo_name: proofixel-docs
repo_url: https://github.com/gotikozzy/proofixel-docs
edit_uri: ""  # Desativa o botão de "editar no github" para usuários finais

# Configuração do Tema (A Mágica acontece aqui)
theme:
  name: material
  language: pt-BR
  logo: assets/logo.png  # Depois você coloca seu logo na pasta docs/assets
  favicon: assets/favicon.ico
  palette: 
    # Modo Escuro (Dark Mode) - Para combinar com o App
    - scheme: slate
      primary: deep-purple    # Cor principal (Botões/Links) - Lembra o Emerald
      accent: indigo     # Cor de destaque
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro
    # Modo Claro (Opcional, se o usuário clicar no solzinho)
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro

  features:
    - navigation.instant   # Navegação super rápida (SPA)
    - navigation.tracking  # Atualiza a URL enquanto rola
    - navigation.top       # Botão "Voltar ao topo"
    - search.suggest       # Sugestões enquanto digita
    - search.highlight     # Marca o texto buscado
    - content.code.copy    # Botão de copiar em blocos de código

# Extensões úteis para escrever bonito
markdown_extensions:
  - admonition        # Caixas de alerta (Info, Warning, Tip)
  - pymdownx.details  # Accordion (Clique para expandir)
  - pymdownx.superfences # Blocos de código avançados
  - attr_list         # Permite alinhar imagens e botões

# Estrutura do Menu (Você vai criando os arquivos depois)
nav:
  - Início: index.md
  - Primeiros Passos:
      - Como criar conta: primeiros-passos/criar-conta.md
      - Comprando Créditos: primeiros-passos/comprar-creditos.md
  - Ferramentas de Análise:
      - Entendendo o ELA: ferramentas/ela.md
      - Metadados: ferramentas/metadados.md
      - Mapa de Calor: ferramentas/heatmap.md
  - Jurídico e Privacidade:
      - Termos de Uso: legal/termos.md
      - Privacidade: legal/privacidade.md
#extra_css:
#  - stylesheets/extra.css      